#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_AIPStressTesting01
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hypdm")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMachineStatuse(MachineStatuse instance);
    partial void UpdateMachineStatuse(MachineStatuse instance);
    partial void DeleteMachineStatuse(MachineStatuse instance);
    partial void InsertSvcParam(SvcParam instance);
    partial void UpdateSvcParam(SvcParam instance);
    partial void DeleteSvcParam(SvcParam instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WPF_AIPStressTesting01.Properties.Settings.Default.hypdmConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MachineStatuse> MachineStatuses
		{
			get
			{
				return this.GetTable<MachineStatuse>();
			}
		}
		
		public System.Data.Linq.Table<SvcParam> SvcParams
		{
			get
			{
				return this.GetTable<SvcParam>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUnprocessedMStatuses")]
		public ISingleResult<GetUnprocessedMStatusesResult> GetUnprocessedMStatuses()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetUnprocessedMStatusesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateMStatus")]
		public int UpdateMStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string machine_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> status_dt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string progname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string properties, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> processed, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> processed_dt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string comment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> only_processed)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, machine_id, status, status_dt, progname, properties, processed, processed_dt, comment, only_processed);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertMStatus")]
		public int InsertMStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string machine_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> status_dt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string progname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string properties, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> processed, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> processed_dt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string comment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, machine_id, status, status_dt, progname, properties, processed, processed_dt, comment);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MachineStatuses")]
	public partial class MachineStatuse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _machine_id;
		
		private int _status;
		
		private System.DateTime _status_dt;
		
		private string _progname;
		
		private string _properties;
		
		private byte _processed;
		
		private System.Nullable<System.DateTime> _processed_dt;
		
		private System.Data.Linq.Binary _ts;
		
		private string _comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmachine_idChanging(string value);
    partial void Onmachine_idChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void Onstatus_dtChanging(System.DateTime value);
    partial void Onstatus_dtChanged();
    partial void OnprognameChanging(string value);
    partial void OnprognameChanged();
    partial void OnpropertiesChanging(string value);
    partial void OnpropertiesChanged();
    partial void OnprocessedChanging(byte value);
    partial void OnprocessedChanged();
    partial void Onprocessed_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onprocessed_dtChanged();
    partial void OntsChanging(System.Data.Linq.Binary value);
    partial void OntsChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    #endregion
		
		public MachineStatuse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machine_id", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string machine_id
		{
			get
			{
				return this._machine_id;
			}
			set
			{
				if ((this._machine_id != value))
				{
					this.Onmachine_idChanging(value);
					this.SendPropertyChanging();
					this._machine_id = value;
					this.SendPropertyChanged("machine_id");
					this.Onmachine_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_dt", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime status_dt
		{
			get
			{
				return this._status_dt;
			}
			set
			{
				if ((this._status_dt != value))
				{
					this.Onstatus_dtChanging(value);
					this.SendPropertyChanging();
					this._status_dt = value;
					this.SendPropertyChanged("status_dt");
					this.Onstatus_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_progname", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string progname
		{
			get
			{
				return this._progname;
			}
			set
			{
				if ((this._progname != value))
				{
					this.OnprognameChanging(value);
					this.SendPropertyChanging();
					this._progname = value;
					this.SendPropertyChanged("progname");
					this.OnprognameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_properties", DbType="NVarChar(1000)", UpdateCheck=UpdateCheck.Never)]
		public string properties
		{
			get
			{
				return this._properties;
			}
			set
			{
				if ((this._properties != value))
				{
					this.OnpropertiesChanging(value);
					this.SendPropertyChanging();
					this._properties = value;
					this.SendPropertyChanged("properties");
					this.OnpropertiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processed", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte processed
		{
			get
			{
				return this._processed;
			}
			set
			{
				if ((this._processed != value))
				{
					this.OnprocessedChanging(value);
					this.SendPropertyChanging();
					this._processed = value;
					this.SendPropertyChanged("processed");
					this.OnprocessedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processed_dt", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> processed_dt
		{
			get
			{
				return this._processed_dt;
			}
			set
			{
				if ((this._processed_dt != value))
				{
					this.Onprocessed_dtChanging(value);
					this.SendPropertyChanging();
					this._processed_dt = value;
					this.SendPropertyChanged("processed_dt");
					this.Onprocessed_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this.OntsChanging(value);
					this.SendPropertyChanging();
					this._ts = value;
					this.SendPropertyChanged("ts");
					this.OntsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SvcParams")]
	public partial class SvcParam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Host;
		
		private string _Instance;
		
		private string _Name;
		
		private string _Value;
		
		private string _Comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHostChanging(string value);
    partial void OnHostChanged();
    partial void OnInstanceChanging(string value);
    partial void OnInstanceChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public SvcParam()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Host", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Host
		{
			get
			{
				return this._Host;
			}
			set
			{
				if ((this._Host != value))
				{
					this.OnHostChanging(value);
					this.SendPropertyChanging();
					this._Host = value;
					this.SendPropertyChanged("Host");
					this.OnHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instance", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Instance
		{
			get
			{
				return this._Instance;
			}
			set
			{
				if ((this._Instance != value))
				{
					this.OnInstanceChanging(value);
					this.SendPropertyChanging();
					this._Instance = value;
					this.SendPropertyChanged("Instance");
					this.OnInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(1000)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetUnprocessedMStatusesResult
	{
		
		private int _id;
		
		private string _machine_id;
		
		private int _status;
		
		private System.DateTime _status_dt;
		
		private string _progname;
		
		private string _properties;
		
		private byte _processed;
		
		private System.Nullable<System.DateTime> _processed_dt;
		
		private string _comment;
		
		public GetUnprocessedMStatusesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machine_id", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string machine_id
		{
			get
			{
				return this._machine_id;
			}
			set
			{
				if ((this._machine_id != value))
				{
					this._machine_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_dt", DbType="DateTime NOT NULL")]
		public System.DateTime status_dt
		{
			get
			{
				return this._status_dt;
			}
			set
			{
				if ((this._status_dt != value))
				{
					this._status_dt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_progname", DbType="NVarChar(50)")]
		public string progname
		{
			get
			{
				return this._progname;
			}
			set
			{
				if ((this._progname != value))
				{
					this._progname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_properties", DbType="NVarChar(1000)")]
		public string properties
		{
			get
			{
				return this._properties;
			}
			set
			{
				if ((this._properties != value))
				{
					this._properties = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processed", DbType="TinyInt NOT NULL")]
		public byte processed
		{
			get
			{
				return this._processed;
			}
			set
			{
				if ((this._processed != value))
				{
					this._processed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processed_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> processed_dt
		{
			get
			{
				return this._processed_dt;
			}
			set
			{
				if ((this._processed_dt != value))
				{
					this._processed_dt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(100)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this._comment = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
