<?xml version="1.0" encoding="utf-8"?><Database Name="hydra1" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MES8N\HYDMS1;Initial Catalog=hydra1;Persist Security Info=True;User ID=sa" SettingsObjectName="WPF_AIPStressTesting01.Properties.Settings" SettingsPropertyName="hydra1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="hydadm.maschinen" Member="maschinens">
    <Type Name="maschinen">
      <Column Name="masch_nr" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="masch_art" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="mgruppe" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="bezeichnung" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="gut" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="gut_impuls" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="gut_zaehl" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="gut_rs232" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="gut_prot" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="gut_manu" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="gut_dim" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="aus" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="aus_impuls" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="aus_zaehl" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="aus_rs232" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="aus_prot" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="aus_manu" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="aus_dim" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="wache_takt" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="wache_zykl" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="wache_sign" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="wachedauer" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="auftr_erfass" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="pers_erfass" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="akkord" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="konf_maske" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="digout1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="digout2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="digout3" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="digout4" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ag01" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ag02" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ag03" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ag04" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="kostenstelle" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="wartezeit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="leistgrad" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="schichtmod" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="mss" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="pss" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="bez_lang" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="kfg_kz01" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="kfg_kz02" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="kfg_kz03" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="kfg_kz04" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="kfg_kz05" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="zielort" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="puffer" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="werk" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="linie" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="voranmeldezeit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pshort_01" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pshort_02" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pshort_03" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pshort_04" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="plong_01" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="plong_02" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="plong_03" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="plong_04" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pdouble_01" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="pdouble_02" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="pdouble_03" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="pdouble_04" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="param_str01" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="param_str02" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="param_str03" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="maxpersonen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vgw01" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="vgs01" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vgw02" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="vgs02" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vgw03" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="vgs03" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vgw04" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="vgs04" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vgw05" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="vgs05" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vgw06" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="vgs06" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="s_subgroup" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_valid_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="s_valid_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="s_co_area" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="s_acti1_unit" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_acti1_uniso" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_noacti1" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="s_acti2_unit" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_acti2_uniso" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_noacti2" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="s_acti3_unit" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_acti3_uniso" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_noacti3" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="s_acti4_unit" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_acti4_uniso" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_noacti4" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="s_acti5_unit" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_acti5_uniso" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_noacti5" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="s_acti6_unit" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_acti6_uniso" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_noacti6" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="s_co_busproc" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="s_co_busproc_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="s_cost_driver" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="s_cost_driver_iso" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="aus_nr_impuls" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="aus_nr_psperre" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="s_teil" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="s_div" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="vl_anzahl" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ortgr" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="firma" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="fremd_apz" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="auto_einlastung" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="vorgabeliste" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="pers_abmeld" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="a_an_sk_beginn" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="planungsfunktion" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="drucker" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="pal_anz_bearb" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pal_umspannzeit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dialogsteuerung" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="symbol" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="ausw_j_mod" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="plan_j_mod" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="kap_j_mod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soll_nutzgrad" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="soll_technutzgrad" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="soll_oee" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="soll_effektivitaet" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="soll_qualitaet" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="soll_produktivitaet" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="user_code" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="user_d_01" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_d_02" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_d_03" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_d_04" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_d_05" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_d_06" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_n_07" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_08" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_09" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_13" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_14" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_15" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_16" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_17" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_18" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_19" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_20" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_21" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_n_22" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_f_23" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="user_f_24" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="user_f_25" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="user_f_26" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="user_f_27" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="user_f_28" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="user_c_29" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_30" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_31" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_32" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_33" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_34" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_35" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_36" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_37" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_38" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_39" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_40" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_41" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_42" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_43" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_44" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="user_c_45" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="user_c_46" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="user_c_47" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="user_c_48" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="user_c_49" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="user_c_50" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="user_c_51" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_52" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_53" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_54" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_55" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_56" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_57" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_58" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_59" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_60" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_61" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_62" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_63" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_64" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_c_65" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="user_c_66" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="bearb" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="bearb_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bearb_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verantw_bereich" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="meinheit_pri" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="meinheit_sek" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="meinheit_ter" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="meinheit_bas" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="umrech_pri_zae" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="umrech_pri_nen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="umrech_sek_zae" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="umrech_sek_nen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="umrech_ter_zae" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="umrech_ter_nen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="verrech_gut" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="verrech_aus" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="verrech_nch" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="verrech_prb" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="gut_manu_takte" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="aus_manu_takte" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="nch_manu_takte" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="prb_manu_takte" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="nch_manu" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="prb_manu" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="vis_list3" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="opt_mdetlg" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="auswmod" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vis_fhm_tnr_a_an" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="bez_lang_1" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="bezeichnung_1" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="bez_lang_2" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="bezeichnung_2" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="bez_lang_18" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="bezeichnung_18" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="hydadm.stoertexte" Member="stoertextes">
    <Type Name="stoertexte">
      <Column Name="stoertxt_nr" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="stoer_text" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="bearb" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="bearb_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bearb_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="farbe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgbcolor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stoer_text_1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="stoer_text_2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="stoer_text_18" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>