#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_AIPStressTesting01
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hydra1")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::WPF_AIPStressTesting01.Properties.Settings.Default.hydra1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<maschinen> maschinens
		{
			get
			{
				return this.GetTable<maschinen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="hydadm.maschinen")]
	public partial class maschinen
	{
		
		private string _masch_nr;
		
		private System.Nullable<char> _masch_art;
		
		private string _mgruppe;
		
		private string _bezeichnung;
		
		private System.Nullable<char> _gut;
		
		private System.Nullable<char> _gut_impuls;
		
		private System.Nullable<short> _gut_zaehl;
		
		private System.Nullable<char> _gut_rs232;
		
		private System.Nullable<short> _gut_prot;
		
		private System.Nullable<char> _gut_manu;
		
		private string _gut_dim;
		
		private System.Nullable<char> _aus;
		
		private System.Nullable<char> _aus_impuls;
		
		private System.Nullable<short> _aus_zaehl;
		
		private System.Nullable<char> _aus_rs232;
		
		private System.Nullable<short> _aus_prot;
		
		private System.Nullable<char> _aus_manu;
		
		private string _aus_dim;
		
		private System.Nullable<char> _wache_takt;
		
		private System.Nullable<short> _wache_zykl;
		
		private System.Nullable<char> _wache_sign;
		
		private System.Nullable<short> _wachedauer;
		
		private System.Nullable<char> _auftr_erfass;
		
		private System.Nullable<char> _pers_erfass;
		
		private System.Nullable<char> _akkord;
		
		private System.Nullable<short> _konf_maske;
		
		private System.Nullable<short> _digout1;
		
		private System.Nullable<short> _digout2;
		
		private System.Nullable<short> _digout3;
		
		private System.Nullable<short> _digout4;
		
		private string _ag01;
		
		private string _ag02;
		
		private string _ag03;
		
		private string _ag04;
		
		private string _kostenstelle;
		
		private System.Nullable<int> _wartezeit;
		
		private System.Nullable<short> _leistgrad;
		
		private System.Nullable<short> _schichtmod;
		
		private System.Nullable<float> _mss;
		
		private System.Nullable<float> _pss;
		
		private string _bez_lang;
		
		private string _kfg_kz01;
		
		private string _kfg_kz02;
		
		private string _kfg_kz03;
		
		private string _kfg_kz04;
		
		private string _kfg_kz05;
		
		private string _zielort;
		
		private string _puffer;
		
		private string _werk;
		
		private string _linie;
		
		private System.Nullable<int> _voranmeldezeit;
		
		private System.Nullable<short> _pshort_01;
		
		private System.Nullable<short> _pshort_02;
		
		private System.Nullable<short> _pshort_03;
		
		private System.Nullable<short> _pshort_04;
		
		private System.Nullable<int> _plong_01;
		
		private System.Nullable<int> _plong_02;
		
		private System.Nullable<int> _plong_03;
		
		private System.Nullable<int> _plong_04;
		
		private System.Nullable<decimal> _pdouble_01;
		
		private System.Nullable<decimal> _pdouble_02;
		
		private System.Nullable<decimal> _pdouble_03;
		
		private System.Nullable<decimal> _pdouble_04;
		
		private string _param_str01;
		
		private string _param_str02;
		
		private string _param_str03;
		
		private System.Nullable<int> _maxpersonen;
		
		private string _vgw01;
		
		private System.Nullable<int> _vgs01;
		
		private string _vgw02;
		
		private System.Nullable<int> _vgs02;
		
		private string _vgw03;
		
		private System.Nullable<int> _vgs03;
		
		private string _vgw04;
		
		private System.Nullable<int> _vgs04;
		
		private string _vgw05;
		
		private System.Nullable<int> _vgs05;
		
		private string _vgw06;
		
		private System.Nullable<int> _vgs06;
		
		private string _s_subgroup;
		
		private System.Nullable<System.DateTime> _s_valid_start;
		
		private System.Nullable<System.DateTime> _s_valid_end;
		
		private string _s_co_area;
		
		private string _s_acti1_unit;
		
		private string _s_acti1_uniso;
		
		private System.Nullable<char> _s_noacti1;
		
		private string _s_acti2_unit;
		
		private string _s_acti2_uniso;
		
		private System.Nullable<char> _s_noacti2;
		
		private string _s_acti3_unit;
		
		private string _s_acti3_uniso;
		
		private System.Nullable<char> _s_noacti3;
		
		private string _s_acti4_unit;
		
		private string _s_acti4_uniso;
		
		private System.Nullable<char> _s_noacti4;
		
		private string _s_acti5_unit;
		
		private string _s_acti5_uniso;
		
		private System.Nullable<char> _s_noacti5;
		
		private string _s_acti6_unit;
		
		private string _s_acti6_uniso;
		
		private System.Nullable<char> _s_noacti6;
		
		private string _s_co_busproc;
		
		private string _s_co_busproc_name;
		
		private string _s_cost_driver;
		
		private string _s_cost_driver_iso;
		
		private System.Nullable<short> _aus_nr_impuls;
		
		private System.Nullable<short> _aus_nr_psperre;
		
		private System.Nullable<decimal> _s_teil;
		
		private System.Nullable<decimal> _s_div;
		
		private System.Nullable<short> _vl_anzahl;
		
		private string _ortgr;
		
		private string _firma;
		
		private System.Nullable<char> _fremd_apz;
		
		private System.Nullable<char> _auto_einlastung;
		
		private System.Nullable<char> _vorgabeliste;
		
		private System.Nullable<char> _pers_abmeld;
		
		private System.Nullable<char> _a_an_sk_beginn;
		
		private System.Nullable<char> _planungsfunktion;
		
		private string _drucker;
		
		private System.Nullable<short> _pal_anz_bearb;
		
		private System.Nullable<int> _pal_umspannzeit;
		
		private string _dialogsteuerung;
		
		private string _symbol;
		
		private System.Nullable<short> _ausw_j_mod;
		
		private System.Nullable<short> _plan_j_mod;
		
		private System.Nullable<int> _kap_j_mod;
		
		private System.Nullable<decimal> _soll_nutzgrad;
		
		private System.Nullable<decimal> _soll_technutzgrad;
		
		private System.Nullable<decimal> _soll_oee;
		
		private System.Nullable<decimal> _soll_effektivitaet;
		
		private System.Nullable<decimal> _soll_qualitaet;
		
		private System.Nullable<decimal> _soll_produktivitaet;
		
		private string _user_code;
		
		private System.Nullable<System.DateTime> _user_d_01;
		
		private System.Nullable<System.DateTime> _user_d_02;
		
		private System.Nullable<System.DateTime> _user_d_03;
		
		private System.Nullable<System.DateTime> _user_d_04;
		
		private System.Nullable<System.DateTime> _user_d_05;
		
		private System.Nullable<System.DateTime> _user_d_06;
		
		private System.Nullable<int> _user_n_07;
		
		private System.Nullable<int> _user_n_08;
		
		private System.Nullable<int> _user_n_09;
		
		private System.Nullable<int> _user_n_10;
		
		private System.Nullable<int> _user_n_11;
		
		private System.Nullable<int> _user_n_12;
		
		private System.Nullable<int> _user_n_13;
		
		private System.Nullable<int> _user_n_14;
		
		private System.Nullable<int> _user_n_15;
		
		private System.Nullable<int> _user_n_16;
		
		private System.Nullable<int> _user_n_17;
		
		private System.Nullable<int> _user_n_18;
		
		private System.Nullable<int> _user_n_19;
		
		private System.Nullable<int> _user_n_20;
		
		private System.Nullable<int> _user_n_21;
		
		private System.Nullable<int> _user_n_22;
		
		private System.Nullable<decimal> _user_f_23;
		
		private System.Nullable<decimal> _user_f_24;
		
		private System.Nullable<decimal> _user_f_25;
		
		private System.Nullable<decimal> _user_f_26;
		
		private System.Nullable<decimal> _user_f_27;
		
		private System.Nullable<decimal> _user_f_28;
		
		private System.Nullable<char> _user_c_29;
		
		private System.Nullable<char> _user_c_30;
		
		private System.Nullable<char> _user_c_31;
		
		private System.Nullable<char> _user_c_32;
		
		private System.Nullable<char> _user_c_33;
		
		private System.Nullable<char> _user_c_34;
		
		private System.Nullable<char> _user_c_35;
		
		private System.Nullable<char> _user_c_36;
		
		private System.Nullable<char> _user_c_37;
		
		private System.Nullable<char> _user_c_38;
		
		private System.Nullable<char> _user_c_39;
		
		private System.Nullable<char> _user_c_40;
		
		private System.Nullable<char> _user_c_41;
		
		private System.Nullable<char> _user_c_42;
		
		private System.Nullable<char> _user_c_43;
		
		private System.Nullable<char> _user_c_44;
		
		private string _user_c_45;
		
		private string _user_c_46;
		
		private string _user_c_47;
		
		private string _user_c_48;
		
		private string _user_c_49;
		
		private string _user_c_50;
		
		private string _user_c_51;
		
		private string _user_c_52;
		
		private string _user_c_53;
		
		private string _user_c_54;
		
		private string _user_c_55;
		
		private string _user_c_56;
		
		private string _user_c_57;
		
		private string _user_c_58;
		
		private string _user_c_59;
		
		private string _user_c_60;
		
		private string _user_c_61;
		
		private string _user_c_62;
		
		private string _user_c_63;
		
		private string _user_c_64;
		
		private string _user_c_65;
		
		private string _user_c_66;
		
		private string _bearb;
		
		private System.Nullable<System.DateTime> _bearb_date;
		
		private System.Nullable<int> _bearb_time;
		
		private string _verantw_bereich;
		
		private string _meinheit_pri;
		
		private string _meinheit_sek;
		
		private string _meinheit_ter;
		
		private string _meinheit_bas;
		
		private System.Nullable<int> _umrech_pri_zae;
		
		private System.Nullable<int> _umrech_pri_nen;
		
		private System.Nullable<int> _umrech_sek_zae;
		
		private System.Nullable<int> _umrech_sek_nen;
		
		private System.Nullable<int> _umrech_ter_zae;
		
		private System.Nullable<int> _umrech_ter_nen;
		
		private string _verrech_gut;
		
		private string _verrech_aus;
		
		private string _verrech_nch;
		
		private string _verrech_prb;
		
		private System.Nullable<char> _gut_manu_takte;
		
		private System.Nullable<char> _aus_manu_takte;
		
		private System.Nullable<char> _nch_manu_takte;
		
		private System.Nullable<char> _prb_manu_takte;
		
		private System.Nullable<char> _nch_manu;
		
		private System.Nullable<char> _prb_manu;
		
		private string _vis_list3;
		
		private System.Nullable<char> _opt_mdetlg;
		
		private System.Nullable<short> _auswmod;
		
		private System.Nullable<char> _vis_fhm_tnr_a_an;
		
		private string _bez_lang_1;
		
		private string _bezeichnung_1;
		
		private string _bez_lang_2;
		
		private string _bezeichnung_2;
		
		private string _bez_lang_18;
		
		private string _bezeichnung_18;
		
		public maschinen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masch_nr", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string masch_nr
		{
			get
			{
				return this._masch_nr;
			}
			set
			{
				if ((this._masch_nr != value))
				{
					this._masch_nr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masch_art", DbType="NChar(1)")]
		public System.Nullable<char> masch_art
		{
			get
			{
				return this._masch_art;
			}
			set
			{
				if ((this._masch_art != value))
				{
					this._masch_art = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mgruppe", DbType="NVarChar(20)")]
		public string mgruppe
		{
			get
			{
				return this._mgruppe;
			}
			set
			{
				if ((this._mgruppe != value))
				{
					this._mgruppe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bezeichnung", DbType="NVarChar(8)")]
		public string bezeichnung
		{
			get
			{
				return this._bezeichnung;
			}
			set
			{
				if ((this._bezeichnung != value))
				{
					this._bezeichnung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gut", DbType="NChar(1)")]
		public System.Nullable<char> gut
		{
			get
			{
				return this._gut;
			}
			set
			{
				if ((this._gut != value))
				{
					this._gut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gut_impuls", DbType="NChar(1)")]
		public System.Nullable<char> gut_impuls
		{
			get
			{
				return this._gut_impuls;
			}
			set
			{
				if ((this._gut_impuls != value))
				{
					this._gut_impuls = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gut_zaehl", DbType="SmallInt")]
		public System.Nullable<short> gut_zaehl
		{
			get
			{
				return this._gut_zaehl;
			}
			set
			{
				if ((this._gut_zaehl != value))
				{
					this._gut_zaehl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gut_rs232", DbType="NChar(1)")]
		public System.Nullable<char> gut_rs232
		{
			get
			{
				return this._gut_rs232;
			}
			set
			{
				if ((this._gut_rs232 != value))
				{
					this._gut_rs232 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gut_prot", DbType="SmallInt")]
		public System.Nullable<short> gut_prot
		{
			get
			{
				return this._gut_prot;
			}
			set
			{
				if ((this._gut_prot != value))
				{
					this._gut_prot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gut_manu", DbType="NChar(1)")]
		public System.Nullable<char> gut_manu
		{
			get
			{
				return this._gut_manu;
			}
			set
			{
				if ((this._gut_manu != value))
				{
					this._gut_manu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gut_dim", DbType="NVarChar(3)")]
		public string gut_dim
		{
			get
			{
				return this._gut_dim;
			}
			set
			{
				if ((this._gut_dim != value))
				{
					this._gut_dim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus", DbType="NChar(1)")]
		public System.Nullable<char> aus
		{
			get
			{
				return this._aus;
			}
			set
			{
				if ((this._aus != value))
				{
					this._aus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_impuls", DbType="NChar(1)")]
		public System.Nullable<char> aus_impuls
		{
			get
			{
				return this._aus_impuls;
			}
			set
			{
				if ((this._aus_impuls != value))
				{
					this._aus_impuls = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_zaehl", DbType="SmallInt")]
		public System.Nullable<short> aus_zaehl
		{
			get
			{
				return this._aus_zaehl;
			}
			set
			{
				if ((this._aus_zaehl != value))
				{
					this._aus_zaehl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_rs232", DbType="NChar(1)")]
		public System.Nullable<char> aus_rs232
		{
			get
			{
				return this._aus_rs232;
			}
			set
			{
				if ((this._aus_rs232 != value))
				{
					this._aus_rs232 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_prot", DbType="SmallInt")]
		public System.Nullable<short> aus_prot
		{
			get
			{
				return this._aus_prot;
			}
			set
			{
				if ((this._aus_prot != value))
				{
					this._aus_prot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_manu", DbType="NChar(1)")]
		public System.Nullable<char> aus_manu
		{
			get
			{
				return this._aus_manu;
			}
			set
			{
				if ((this._aus_manu != value))
				{
					this._aus_manu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_dim", DbType="NVarChar(3)")]
		public string aus_dim
		{
			get
			{
				return this._aus_dim;
			}
			set
			{
				if ((this._aus_dim != value))
				{
					this._aus_dim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wache_takt", DbType="NChar(1)")]
		public System.Nullable<char> wache_takt
		{
			get
			{
				return this._wache_takt;
			}
			set
			{
				if ((this._wache_takt != value))
				{
					this._wache_takt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wache_zykl", DbType="SmallInt")]
		public System.Nullable<short> wache_zykl
		{
			get
			{
				return this._wache_zykl;
			}
			set
			{
				if ((this._wache_zykl != value))
				{
					this._wache_zykl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wache_sign", DbType="NChar(1)")]
		public System.Nullable<char> wache_sign
		{
			get
			{
				return this._wache_sign;
			}
			set
			{
				if ((this._wache_sign != value))
				{
					this._wache_sign = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wachedauer", DbType="SmallInt")]
		public System.Nullable<short> wachedauer
		{
			get
			{
				return this._wachedauer;
			}
			set
			{
				if ((this._wachedauer != value))
				{
					this._wachedauer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auftr_erfass", DbType="NChar(1)")]
		public System.Nullable<char> auftr_erfass
		{
			get
			{
				return this._auftr_erfass;
			}
			set
			{
				if ((this._auftr_erfass != value))
				{
					this._auftr_erfass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pers_erfass", DbType="NChar(1)")]
		public System.Nullable<char> pers_erfass
		{
			get
			{
				return this._pers_erfass;
			}
			set
			{
				if ((this._pers_erfass != value))
				{
					this._pers_erfass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_akkord", DbType="NChar(1)")]
		public System.Nullable<char> akkord
		{
			get
			{
				return this._akkord;
			}
			set
			{
				if ((this._akkord != value))
				{
					this._akkord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_konf_maske", DbType="SmallInt")]
		public System.Nullable<short> konf_maske
		{
			get
			{
				return this._konf_maske;
			}
			set
			{
				if ((this._konf_maske != value))
				{
					this._konf_maske = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_digout1", DbType="SmallInt")]
		public System.Nullable<short> digout1
		{
			get
			{
				return this._digout1;
			}
			set
			{
				if ((this._digout1 != value))
				{
					this._digout1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_digout2", DbType="SmallInt")]
		public System.Nullable<short> digout2
		{
			get
			{
				return this._digout2;
			}
			set
			{
				if ((this._digout2 != value))
				{
					this._digout2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_digout3", DbType="SmallInt")]
		public System.Nullable<short> digout3
		{
			get
			{
				return this._digout3;
			}
			set
			{
				if ((this._digout3 != value))
				{
					this._digout3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_digout4", DbType="SmallInt")]
		public System.Nullable<short> digout4
		{
			get
			{
				return this._digout4;
			}
			set
			{
				if ((this._digout4 != value))
				{
					this._digout4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ag01", DbType="NVarChar(4)")]
		public string ag01
		{
			get
			{
				return this._ag01;
			}
			set
			{
				if ((this._ag01 != value))
				{
					this._ag01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ag02", DbType="NVarChar(4)")]
		public string ag02
		{
			get
			{
				return this._ag02;
			}
			set
			{
				if ((this._ag02 != value))
				{
					this._ag02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ag03", DbType="NVarChar(4)")]
		public string ag03
		{
			get
			{
				return this._ag03;
			}
			set
			{
				if ((this._ag03 != value))
				{
					this._ag03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ag04", DbType="NVarChar(4)")]
		public string ag04
		{
			get
			{
				return this._ag04;
			}
			set
			{
				if ((this._ag04 != value))
				{
					this._ag04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kostenstelle", DbType="NVarChar(10)")]
		public string kostenstelle
		{
			get
			{
				return this._kostenstelle;
			}
			set
			{
				if ((this._kostenstelle != value))
				{
					this._kostenstelle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wartezeit", DbType="Int")]
		public System.Nullable<int> wartezeit
		{
			get
			{
				return this._wartezeit;
			}
			set
			{
				if ((this._wartezeit != value))
				{
					this._wartezeit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leistgrad", DbType="SmallInt")]
		public System.Nullable<short> leistgrad
		{
			get
			{
				return this._leistgrad;
			}
			set
			{
				if ((this._leistgrad != value))
				{
					this._leistgrad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schichtmod", DbType="SmallInt")]
		public System.Nullable<short> schichtmod
		{
			get
			{
				return this._schichtmod;
			}
			set
			{
				if ((this._schichtmod != value))
				{
					this._schichtmod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mss", DbType="Real")]
		public System.Nullable<float> mss
		{
			get
			{
				return this._mss;
			}
			set
			{
				if ((this._mss != value))
				{
					this._mss = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pss", DbType="Real")]
		public System.Nullable<float> pss
		{
			get
			{
				return this._pss;
			}
			set
			{
				if ((this._pss != value))
				{
					this._pss = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bez_lang", DbType="NVarChar(40)")]
		public string bez_lang
		{
			get
			{
				return this._bez_lang;
			}
			set
			{
				if ((this._bez_lang != value))
				{
					this._bez_lang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kfg_kz01", DbType="NVarChar(5)")]
		public string kfg_kz01
		{
			get
			{
				return this._kfg_kz01;
			}
			set
			{
				if ((this._kfg_kz01 != value))
				{
					this._kfg_kz01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kfg_kz02", DbType="NVarChar(5)")]
		public string kfg_kz02
		{
			get
			{
				return this._kfg_kz02;
			}
			set
			{
				if ((this._kfg_kz02 != value))
				{
					this._kfg_kz02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kfg_kz03", DbType="NVarChar(5)")]
		public string kfg_kz03
		{
			get
			{
				return this._kfg_kz03;
			}
			set
			{
				if ((this._kfg_kz03 != value))
				{
					this._kfg_kz03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kfg_kz04", DbType="NVarChar(5)")]
		public string kfg_kz04
		{
			get
			{
				return this._kfg_kz04;
			}
			set
			{
				if ((this._kfg_kz04 != value))
				{
					this._kfg_kz04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kfg_kz05", DbType="NVarChar(5)")]
		public string kfg_kz05
		{
			get
			{
				return this._kfg_kz05;
			}
			set
			{
				if ((this._kfg_kz05 != value))
				{
					this._kfg_kz05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zielort", DbType="NVarChar(12)")]
		public string zielort
		{
			get
			{
				return this._zielort;
			}
			set
			{
				if ((this._zielort != value))
				{
					this._zielort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puffer", DbType="NVarChar(12)")]
		public string puffer
		{
			get
			{
				return this._puffer;
			}
			set
			{
				if ((this._puffer != value))
				{
					this._puffer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_werk", DbType="NVarChar(10)")]
		public string werk
		{
			get
			{
				return this._werk;
			}
			set
			{
				if ((this._werk != value))
				{
					this._werk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linie", DbType="NVarChar(10)")]
		public string linie
		{
			get
			{
				return this._linie;
			}
			set
			{
				if ((this._linie != value))
				{
					this._linie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voranmeldezeit", DbType="Int")]
		public System.Nullable<int> voranmeldezeit
		{
			get
			{
				return this._voranmeldezeit;
			}
			set
			{
				if ((this._voranmeldezeit != value))
				{
					this._voranmeldezeit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pshort_01", DbType="SmallInt")]
		public System.Nullable<short> pshort_01
		{
			get
			{
				return this._pshort_01;
			}
			set
			{
				if ((this._pshort_01 != value))
				{
					this._pshort_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pshort_02", DbType="SmallInt")]
		public System.Nullable<short> pshort_02
		{
			get
			{
				return this._pshort_02;
			}
			set
			{
				if ((this._pshort_02 != value))
				{
					this._pshort_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pshort_03", DbType="SmallInt")]
		public System.Nullable<short> pshort_03
		{
			get
			{
				return this._pshort_03;
			}
			set
			{
				if ((this._pshort_03 != value))
				{
					this._pshort_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pshort_04", DbType="SmallInt")]
		public System.Nullable<short> pshort_04
		{
			get
			{
				return this._pshort_04;
			}
			set
			{
				if ((this._pshort_04 != value))
				{
					this._pshort_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plong_01", DbType="Int")]
		public System.Nullable<int> plong_01
		{
			get
			{
				return this._plong_01;
			}
			set
			{
				if ((this._plong_01 != value))
				{
					this._plong_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plong_02", DbType="Int")]
		public System.Nullable<int> plong_02
		{
			get
			{
				return this._plong_02;
			}
			set
			{
				if ((this._plong_02 != value))
				{
					this._plong_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plong_03", DbType="Int")]
		public System.Nullable<int> plong_03
		{
			get
			{
				return this._plong_03;
			}
			set
			{
				if ((this._plong_03 != value))
				{
					this._plong_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plong_04", DbType="Int")]
		public System.Nullable<int> plong_04
		{
			get
			{
				return this._plong_04;
			}
			set
			{
				if ((this._plong_04 != value))
				{
					this._plong_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdouble_01", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> pdouble_01
		{
			get
			{
				return this._pdouble_01;
			}
			set
			{
				if ((this._pdouble_01 != value))
				{
					this._pdouble_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdouble_02", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> pdouble_02
		{
			get
			{
				return this._pdouble_02;
			}
			set
			{
				if ((this._pdouble_02 != value))
				{
					this._pdouble_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdouble_03", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> pdouble_03
		{
			get
			{
				return this._pdouble_03;
			}
			set
			{
				if ((this._pdouble_03 != value))
				{
					this._pdouble_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdouble_04", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> pdouble_04
		{
			get
			{
				return this._pdouble_04;
			}
			set
			{
				if ((this._pdouble_04 != value))
				{
					this._pdouble_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param_str01", DbType="NVarChar(10)")]
		public string param_str01
		{
			get
			{
				return this._param_str01;
			}
			set
			{
				if ((this._param_str01 != value))
				{
					this._param_str01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param_str02", DbType="NVarChar(10)")]
		public string param_str02
		{
			get
			{
				return this._param_str02;
			}
			set
			{
				if ((this._param_str02 != value))
				{
					this._param_str02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_param_str03", DbType="NVarChar(30)")]
		public string param_str03
		{
			get
			{
				return this._param_str03;
			}
			set
			{
				if ((this._param_str03 != value))
				{
					this._param_str03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxpersonen", DbType="Int")]
		public System.Nullable<int> maxpersonen
		{
			get
			{
				return this._maxpersonen;
			}
			set
			{
				if ((this._maxpersonen != value))
				{
					this._maxpersonen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgw01", DbType="NVarChar(20)")]
		public string vgw01
		{
			get
			{
				return this._vgw01;
			}
			set
			{
				if ((this._vgw01 != value))
				{
					this._vgw01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgs01", DbType="Int")]
		public System.Nullable<int> vgs01
		{
			get
			{
				return this._vgs01;
			}
			set
			{
				if ((this._vgs01 != value))
				{
					this._vgs01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgw02", DbType="NVarChar(20)")]
		public string vgw02
		{
			get
			{
				return this._vgw02;
			}
			set
			{
				if ((this._vgw02 != value))
				{
					this._vgw02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgs02", DbType="Int")]
		public System.Nullable<int> vgs02
		{
			get
			{
				return this._vgs02;
			}
			set
			{
				if ((this._vgs02 != value))
				{
					this._vgs02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgw03", DbType="NVarChar(20)")]
		public string vgw03
		{
			get
			{
				return this._vgw03;
			}
			set
			{
				if ((this._vgw03 != value))
				{
					this._vgw03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgs03", DbType="Int")]
		public System.Nullable<int> vgs03
		{
			get
			{
				return this._vgs03;
			}
			set
			{
				if ((this._vgs03 != value))
				{
					this._vgs03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgw04", DbType="NVarChar(20)")]
		public string vgw04
		{
			get
			{
				return this._vgw04;
			}
			set
			{
				if ((this._vgw04 != value))
				{
					this._vgw04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgs04", DbType="Int")]
		public System.Nullable<int> vgs04
		{
			get
			{
				return this._vgs04;
			}
			set
			{
				if ((this._vgs04 != value))
				{
					this._vgs04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgw05", DbType="NVarChar(20)")]
		public string vgw05
		{
			get
			{
				return this._vgw05;
			}
			set
			{
				if ((this._vgw05 != value))
				{
					this._vgw05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgs05", DbType="Int")]
		public System.Nullable<int> vgs05
		{
			get
			{
				return this._vgs05;
			}
			set
			{
				if ((this._vgs05 != value))
				{
					this._vgs05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgw06", DbType="NVarChar(20)")]
		public string vgw06
		{
			get
			{
				return this._vgw06;
			}
			set
			{
				if ((this._vgw06 != value))
				{
					this._vgw06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vgs06", DbType="Int")]
		public System.Nullable<int> vgs06
		{
			get
			{
				return this._vgs06;
			}
			set
			{
				if ((this._vgs06 != value))
				{
					this._vgs06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_subgroup", DbType="NVarChar(3)")]
		public string s_subgroup
		{
			get
			{
				return this._s_subgroup;
			}
			set
			{
				if ((this._s_subgroup != value))
				{
					this._s_subgroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_valid_start", DbType="DateTime")]
		public System.Nullable<System.DateTime> s_valid_start
		{
			get
			{
				return this._s_valid_start;
			}
			set
			{
				if ((this._s_valid_start != value))
				{
					this._s_valid_start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_valid_end", DbType="DateTime")]
		public System.Nullable<System.DateTime> s_valid_end
		{
			get
			{
				return this._s_valid_end;
			}
			set
			{
				if ((this._s_valid_end != value))
				{
					this._s_valid_end = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_co_area", DbType="NVarChar(4)")]
		public string s_co_area
		{
			get
			{
				return this._s_co_area;
			}
			set
			{
				if ((this._s_co_area != value))
				{
					this._s_co_area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti1_unit", DbType="NVarChar(3)")]
		public string s_acti1_unit
		{
			get
			{
				return this._s_acti1_unit;
			}
			set
			{
				if ((this._s_acti1_unit != value))
				{
					this._s_acti1_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti1_uniso", DbType="NVarChar(3)")]
		public string s_acti1_uniso
		{
			get
			{
				return this._s_acti1_uniso;
			}
			set
			{
				if ((this._s_acti1_uniso != value))
				{
					this._s_acti1_uniso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_noacti1", DbType="NChar(1)")]
		public System.Nullable<char> s_noacti1
		{
			get
			{
				return this._s_noacti1;
			}
			set
			{
				if ((this._s_noacti1 != value))
				{
					this._s_noacti1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti2_unit", DbType="NVarChar(3)")]
		public string s_acti2_unit
		{
			get
			{
				return this._s_acti2_unit;
			}
			set
			{
				if ((this._s_acti2_unit != value))
				{
					this._s_acti2_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti2_uniso", DbType="NVarChar(3)")]
		public string s_acti2_uniso
		{
			get
			{
				return this._s_acti2_uniso;
			}
			set
			{
				if ((this._s_acti2_uniso != value))
				{
					this._s_acti2_uniso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_noacti2", DbType="NChar(1)")]
		public System.Nullable<char> s_noacti2
		{
			get
			{
				return this._s_noacti2;
			}
			set
			{
				if ((this._s_noacti2 != value))
				{
					this._s_noacti2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti3_unit", DbType="NVarChar(3)")]
		public string s_acti3_unit
		{
			get
			{
				return this._s_acti3_unit;
			}
			set
			{
				if ((this._s_acti3_unit != value))
				{
					this._s_acti3_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti3_uniso", DbType="NVarChar(3)")]
		public string s_acti3_uniso
		{
			get
			{
				return this._s_acti3_uniso;
			}
			set
			{
				if ((this._s_acti3_uniso != value))
				{
					this._s_acti3_uniso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_noacti3", DbType="NChar(1)")]
		public System.Nullable<char> s_noacti3
		{
			get
			{
				return this._s_noacti3;
			}
			set
			{
				if ((this._s_noacti3 != value))
				{
					this._s_noacti3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti4_unit", DbType="NVarChar(3)")]
		public string s_acti4_unit
		{
			get
			{
				return this._s_acti4_unit;
			}
			set
			{
				if ((this._s_acti4_unit != value))
				{
					this._s_acti4_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti4_uniso", DbType="NVarChar(3)")]
		public string s_acti4_uniso
		{
			get
			{
				return this._s_acti4_uniso;
			}
			set
			{
				if ((this._s_acti4_uniso != value))
				{
					this._s_acti4_uniso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_noacti4", DbType="NChar(1)")]
		public System.Nullable<char> s_noacti4
		{
			get
			{
				return this._s_noacti4;
			}
			set
			{
				if ((this._s_noacti4 != value))
				{
					this._s_noacti4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti5_unit", DbType="NVarChar(3)")]
		public string s_acti5_unit
		{
			get
			{
				return this._s_acti5_unit;
			}
			set
			{
				if ((this._s_acti5_unit != value))
				{
					this._s_acti5_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti5_uniso", DbType="NVarChar(3)")]
		public string s_acti5_uniso
		{
			get
			{
				return this._s_acti5_uniso;
			}
			set
			{
				if ((this._s_acti5_uniso != value))
				{
					this._s_acti5_uniso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_noacti5", DbType="NChar(1)")]
		public System.Nullable<char> s_noacti5
		{
			get
			{
				return this._s_noacti5;
			}
			set
			{
				if ((this._s_noacti5 != value))
				{
					this._s_noacti5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti6_unit", DbType="NVarChar(3)")]
		public string s_acti6_unit
		{
			get
			{
				return this._s_acti6_unit;
			}
			set
			{
				if ((this._s_acti6_unit != value))
				{
					this._s_acti6_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_acti6_uniso", DbType="NVarChar(3)")]
		public string s_acti6_uniso
		{
			get
			{
				return this._s_acti6_uniso;
			}
			set
			{
				if ((this._s_acti6_uniso != value))
				{
					this._s_acti6_uniso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_noacti6", DbType="NChar(1)")]
		public System.Nullable<char> s_noacti6
		{
			get
			{
				return this._s_noacti6;
			}
			set
			{
				if ((this._s_noacti6 != value))
				{
					this._s_noacti6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_co_busproc", DbType="NVarChar(12)")]
		public string s_co_busproc
		{
			get
			{
				return this._s_co_busproc;
			}
			set
			{
				if ((this._s_co_busproc != value))
				{
					this._s_co_busproc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_co_busproc_name", DbType="NVarChar(20)")]
		public string s_co_busproc_name
		{
			get
			{
				return this._s_co_busproc_name;
			}
			set
			{
				if ((this._s_co_busproc_name != value))
				{
					this._s_co_busproc_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_cost_driver", DbType="NVarChar(3)")]
		public string s_cost_driver
		{
			get
			{
				return this._s_cost_driver;
			}
			set
			{
				if ((this._s_cost_driver != value))
				{
					this._s_cost_driver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_cost_driver_iso", DbType="NVarChar(3)")]
		public string s_cost_driver_iso
		{
			get
			{
				return this._s_cost_driver_iso;
			}
			set
			{
				if ((this._s_cost_driver_iso != value))
				{
					this._s_cost_driver_iso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_nr_impuls", DbType="SmallInt")]
		public System.Nullable<short> aus_nr_impuls
		{
			get
			{
				return this._aus_nr_impuls;
			}
			set
			{
				if ((this._aus_nr_impuls != value))
				{
					this._aus_nr_impuls = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_nr_psperre", DbType="SmallInt")]
		public System.Nullable<short> aus_nr_psperre
		{
			get
			{
				return this._aus_nr_psperre;
			}
			set
			{
				if ((this._aus_nr_psperre != value))
				{
					this._aus_nr_psperre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_teil", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> s_teil
		{
			get
			{
				return this._s_teil;
			}
			set
			{
				if ((this._s_teil != value))
				{
					this._s_teil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_div", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> s_div
		{
			get
			{
				return this._s_div;
			}
			set
			{
				if ((this._s_div != value))
				{
					this._s_div = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vl_anzahl", DbType="SmallInt")]
		public System.Nullable<short> vl_anzahl
		{
			get
			{
				return this._vl_anzahl;
			}
			set
			{
				if ((this._vl_anzahl != value))
				{
					this._vl_anzahl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ortgr", DbType="NVarChar(4)")]
		public string ortgr
		{
			get
			{
				return this._ortgr;
			}
			set
			{
				if ((this._ortgr != value))
				{
					this._ortgr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma", DbType="NVarChar(4)")]
		public string firma
		{
			get
			{
				return this._firma;
			}
			set
			{
				if ((this._firma != value))
				{
					this._firma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fremd_apz", DbType="NChar(1)")]
		public System.Nullable<char> fremd_apz
		{
			get
			{
				return this._fremd_apz;
			}
			set
			{
				if ((this._fremd_apz != value))
				{
					this._fremd_apz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auto_einlastung", DbType="NChar(1)")]
		public System.Nullable<char> auto_einlastung
		{
			get
			{
				return this._auto_einlastung;
			}
			set
			{
				if ((this._auto_einlastung != value))
				{
					this._auto_einlastung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorgabeliste", DbType="NChar(1)")]
		public System.Nullable<char> vorgabeliste
		{
			get
			{
				return this._vorgabeliste;
			}
			set
			{
				if ((this._vorgabeliste != value))
				{
					this._vorgabeliste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pers_abmeld", DbType="NChar(1)")]
		public System.Nullable<char> pers_abmeld
		{
			get
			{
				return this._pers_abmeld;
			}
			set
			{
				if ((this._pers_abmeld != value))
				{
					this._pers_abmeld = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_an_sk_beginn", DbType="NChar(1)")]
		public System.Nullable<char> a_an_sk_beginn
		{
			get
			{
				return this._a_an_sk_beginn;
			}
			set
			{
				if ((this._a_an_sk_beginn != value))
				{
					this._a_an_sk_beginn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planungsfunktion", DbType="NChar(1)")]
		public System.Nullable<char> planungsfunktion
		{
			get
			{
				return this._planungsfunktion;
			}
			set
			{
				if ((this._planungsfunktion != value))
				{
					this._planungsfunktion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drucker", DbType="NVarChar(100)")]
		public string drucker
		{
			get
			{
				return this._drucker;
			}
			set
			{
				if ((this._drucker != value))
				{
					this._drucker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pal_anz_bearb", DbType="SmallInt")]
		public System.Nullable<short> pal_anz_bearb
		{
			get
			{
				return this._pal_anz_bearb;
			}
			set
			{
				if ((this._pal_anz_bearb != value))
				{
					this._pal_anz_bearb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pal_umspannzeit", DbType="Int")]
		public System.Nullable<int> pal_umspannzeit
		{
			get
			{
				return this._pal_umspannzeit;
			}
			set
			{
				if ((this._pal_umspannzeit != value))
				{
					this._pal_umspannzeit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dialogsteuerung", DbType="NVarChar(10)")]
		public string dialogsteuerung
		{
			get
			{
				return this._dialogsteuerung;
			}
			set
			{
				if ((this._dialogsteuerung != value))
				{
					this._dialogsteuerung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="NVarChar(12)")]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					this._symbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ausw_j_mod", DbType="SmallInt")]
		public System.Nullable<short> ausw_j_mod
		{
			get
			{
				return this._ausw_j_mod;
			}
			set
			{
				if ((this._ausw_j_mod != value))
				{
					this._ausw_j_mod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_j_mod", DbType="SmallInt")]
		public System.Nullable<short> plan_j_mod
		{
			get
			{
				return this._plan_j_mod;
			}
			set
			{
				if ((this._plan_j_mod != value))
				{
					this._plan_j_mod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kap_j_mod", DbType="Int")]
		public System.Nullable<int> kap_j_mod
		{
			get
			{
				return this._kap_j_mod;
			}
			set
			{
				if ((this._kap_j_mod != value))
				{
					this._kap_j_mod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soll_nutzgrad", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> soll_nutzgrad
		{
			get
			{
				return this._soll_nutzgrad;
			}
			set
			{
				if ((this._soll_nutzgrad != value))
				{
					this._soll_nutzgrad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soll_technutzgrad", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> soll_technutzgrad
		{
			get
			{
				return this._soll_technutzgrad;
			}
			set
			{
				if ((this._soll_technutzgrad != value))
				{
					this._soll_technutzgrad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soll_oee", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> soll_oee
		{
			get
			{
				return this._soll_oee;
			}
			set
			{
				if ((this._soll_oee != value))
				{
					this._soll_oee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soll_effektivitaet", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> soll_effektivitaet
		{
			get
			{
				return this._soll_effektivitaet;
			}
			set
			{
				if ((this._soll_effektivitaet != value))
				{
					this._soll_effektivitaet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soll_qualitaet", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> soll_qualitaet
		{
			get
			{
				return this._soll_qualitaet;
			}
			set
			{
				if ((this._soll_qualitaet != value))
				{
					this._soll_qualitaet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soll_produktivitaet", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> soll_produktivitaet
		{
			get
			{
				return this._soll_produktivitaet;
			}
			set
			{
				if ((this._soll_produktivitaet != value))
				{
					this._soll_produktivitaet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_code", DbType="NVarChar(8)")]
		public string user_code
		{
			get
			{
				return this._user_code;
			}
			set
			{
				if ((this._user_code != value))
				{
					this._user_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_d_01", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_d_01
		{
			get
			{
				return this._user_d_01;
			}
			set
			{
				if ((this._user_d_01 != value))
				{
					this._user_d_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_d_02", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_d_02
		{
			get
			{
				return this._user_d_02;
			}
			set
			{
				if ((this._user_d_02 != value))
				{
					this._user_d_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_d_03", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_d_03
		{
			get
			{
				return this._user_d_03;
			}
			set
			{
				if ((this._user_d_03 != value))
				{
					this._user_d_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_d_04", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_d_04
		{
			get
			{
				return this._user_d_04;
			}
			set
			{
				if ((this._user_d_04 != value))
				{
					this._user_d_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_d_05", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_d_05
		{
			get
			{
				return this._user_d_05;
			}
			set
			{
				if ((this._user_d_05 != value))
				{
					this._user_d_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_d_06", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_d_06
		{
			get
			{
				return this._user_d_06;
			}
			set
			{
				if ((this._user_d_06 != value))
				{
					this._user_d_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_07", DbType="Int")]
		public System.Nullable<int> user_n_07
		{
			get
			{
				return this._user_n_07;
			}
			set
			{
				if ((this._user_n_07 != value))
				{
					this._user_n_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_08", DbType="Int")]
		public System.Nullable<int> user_n_08
		{
			get
			{
				return this._user_n_08;
			}
			set
			{
				if ((this._user_n_08 != value))
				{
					this._user_n_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_09", DbType="Int")]
		public System.Nullable<int> user_n_09
		{
			get
			{
				return this._user_n_09;
			}
			set
			{
				if ((this._user_n_09 != value))
				{
					this._user_n_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_10", DbType="Int")]
		public System.Nullable<int> user_n_10
		{
			get
			{
				return this._user_n_10;
			}
			set
			{
				if ((this._user_n_10 != value))
				{
					this._user_n_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_11", DbType="Int")]
		public System.Nullable<int> user_n_11
		{
			get
			{
				return this._user_n_11;
			}
			set
			{
				if ((this._user_n_11 != value))
				{
					this._user_n_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_12", DbType="Int")]
		public System.Nullable<int> user_n_12
		{
			get
			{
				return this._user_n_12;
			}
			set
			{
				if ((this._user_n_12 != value))
				{
					this._user_n_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_13", DbType="Int")]
		public System.Nullable<int> user_n_13
		{
			get
			{
				return this._user_n_13;
			}
			set
			{
				if ((this._user_n_13 != value))
				{
					this._user_n_13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_14", DbType="Int")]
		public System.Nullable<int> user_n_14
		{
			get
			{
				return this._user_n_14;
			}
			set
			{
				if ((this._user_n_14 != value))
				{
					this._user_n_14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_15", DbType="Int")]
		public System.Nullable<int> user_n_15
		{
			get
			{
				return this._user_n_15;
			}
			set
			{
				if ((this._user_n_15 != value))
				{
					this._user_n_15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_16", DbType="Int")]
		public System.Nullable<int> user_n_16
		{
			get
			{
				return this._user_n_16;
			}
			set
			{
				if ((this._user_n_16 != value))
				{
					this._user_n_16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_17", DbType="Int")]
		public System.Nullable<int> user_n_17
		{
			get
			{
				return this._user_n_17;
			}
			set
			{
				if ((this._user_n_17 != value))
				{
					this._user_n_17 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_18", DbType="Int")]
		public System.Nullable<int> user_n_18
		{
			get
			{
				return this._user_n_18;
			}
			set
			{
				if ((this._user_n_18 != value))
				{
					this._user_n_18 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_19", DbType="Int")]
		public System.Nullable<int> user_n_19
		{
			get
			{
				return this._user_n_19;
			}
			set
			{
				if ((this._user_n_19 != value))
				{
					this._user_n_19 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_20", DbType="Int")]
		public System.Nullable<int> user_n_20
		{
			get
			{
				return this._user_n_20;
			}
			set
			{
				if ((this._user_n_20 != value))
				{
					this._user_n_20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_21", DbType="Int")]
		public System.Nullable<int> user_n_21
		{
			get
			{
				return this._user_n_21;
			}
			set
			{
				if ((this._user_n_21 != value))
				{
					this._user_n_21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_n_22", DbType="Int")]
		public System.Nullable<int> user_n_22
		{
			get
			{
				return this._user_n_22;
			}
			set
			{
				if ((this._user_n_22 != value))
				{
					this._user_n_22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_f_23", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> user_f_23
		{
			get
			{
				return this._user_f_23;
			}
			set
			{
				if ((this._user_f_23 != value))
				{
					this._user_f_23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_f_24", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> user_f_24
		{
			get
			{
				return this._user_f_24;
			}
			set
			{
				if ((this._user_f_24 != value))
				{
					this._user_f_24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_f_25", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> user_f_25
		{
			get
			{
				return this._user_f_25;
			}
			set
			{
				if ((this._user_f_25 != value))
				{
					this._user_f_25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_f_26", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> user_f_26
		{
			get
			{
				return this._user_f_26;
			}
			set
			{
				if ((this._user_f_26 != value))
				{
					this._user_f_26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_f_27", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> user_f_27
		{
			get
			{
				return this._user_f_27;
			}
			set
			{
				if ((this._user_f_27 != value))
				{
					this._user_f_27 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_f_28", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> user_f_28
		{
			get
			{
				return this._user_f_28;
			}
			set
			{
				if ((this._user_f_28 != value))
				{
					this._user_f_28 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_29", DbType="NChar(1)")]
		public System.Nullable<char> user_c_29
		{
			get
			{
				return this._user_c_29;
			}
			set
			{
				if ((this._user_c_29 != value))
				{
					this._user_c_29 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_30", DbType="NChar(1)")]
		public System.Nullable<char> user_c_30
		{
			get
			{
				return this._user_c_30;
			}
			set
			{
				if ((this._user_c_30 != value))
				{
					this._user_c_30 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_31", DbType="NChar(1)")]
		public System.Nullable<char> user_c_31
		{
			get
			{
				return this._user_c_31;
			}
			set
			{
				if ((this._user_c_31 != value))
				{
					this._user_c_31 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_32", DbType="NChar(1)")]
		public System.Nullable<char> user_c_32
		{
			get
			{
				return this._user_c_32;
			}
			set
			{
				if ((this._user_c_32 != value))
				{
					this._user_c_32 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_33", DbType="NChar(1)")]
		public System.Nullable<char> user_c_33
		{
			get
			{
				return this._user_c_33;
			}
			set
			{
				if ((this._user_c_33 != value))
				{
					this._user_c_33 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_34", DbType="NChar(1)")]
		public System.Nullable<char> user_c_34
		{
			get
			{
				return this._user_c_34;
			}
			set
			{
				if ((this._user_c_34 != value))
				{
					this._user_c_34 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_35", DbType="NChar(1)")]
		public System.Nullable<char> user_c_35
		{
			get
			{
				return this._user_c_35;
			}
			set
			{
				if ((this._user_c_35 != value))
				{
					this._user_c_35 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_36", DbType="NChar(1)")]
		public System.Nullable<char> user_c_36
		{
			get
			{
				return this._user_c_36;
			}
			set
			{
				if ((this._user_c_36 != value))
				{
					this._user_c_36 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_37", DbType="NChar(1)")]
		public System.Nullable<char> user_c_37
		{
			get
			{
				return this._user_c_37;
			}
			set
			{
				if ((this._user_c_37 != value))
				{
					this._user_c_37 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_38", DbType="NChar(1)")]
		public System.Nullable<char> user_c_38
		{
			get
			{
				return this._user_c_38;
			}
			set
			{
				if ((this._user_c_38 != value))
				{
					this._user_c_38 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_39", DbType="NChar(1)")]
		public System.Nullable<char> user_c_39
		{
			get
			{
				return this._user_c_39;
			}
			set
			{
				if ((this._user_c_39 != value))
				{
					this._user_c_39 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_40", DbType="NChar(1)")]
		public System.Nullable<char> user_c_40
		{
			get
			{
				return this._user_c_40;
			}
			set
			{
				if ((this._user_c_40 != value))
				{
					this._user_c_40 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_41", DbType="NChar(1)")]
		public System.Nullable<char> user_c_41
		{
			get
			{
				return this._user_c_41;
			}
			set
			{
				if ((this._user_c_41 != value))
				{
					this._user_c_41 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_42", DbType="NChar(1)")]
		public System.Nullable<char> user_c_42
		{
			get
			{
				return this._user_c_42;
			}
			set
			{
				if ((this._user_c_42 != value))
				{
					this._user_c_42 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_43", DbType="NChar(1)")]
		public System.Nullable<char> user_c_43
		{
			get
			{
				return this._user_c_43;
			}
			set
			{
				if ((this._user_c_43 != value))
				{
					this._user_c_43 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_44", DbType="NChar(1)")]
		public System.Nullable<char> user_c_44
		{
			get
			{
				return this._user_c_44;
			}
			set
			{
				if ((this._user_c_44 != value))
				{
					this._user_c_44 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_45", DbType="NVarChar(10)")]
		public string user_c_45
		{
			get
			{
				return this._user_c_45;
			}
			set
			{
				if ((this._user_c_45 != value))
				{
					this._user_c_45 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_46", DbType="NVarChar(10)")]
		public string user_c_46
		{
			get
			{
				return this._user_c_46;
			}
			set
			{
				if ((this._user_c_46 != value))
				{
					this._user_c_46 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_47", DbType="NVarChar(10)")]
		public string user_c_47
		{
			get
			{
				return this._user_c_47;
			}
			set
			{
				if ((this._user_c_47 != value))
				{
					this._user_c_47 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_48", DbType="NVarChar(10)")]
		public string user_c_48
		{
			get
			{
				return this._user_c_48;
			}
			set
			{
				if ((this._user_c_48 != value))
				{
					this._user_c_48 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_49", DbType="NVarChar(10)")]
		public string user_c_49
		{
			get
			{
				return this._user_c_49;
			}
			set
			{
				if ((this._user_c_49 != value))
				{
					this._user_c_49 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_50", DbType="NVarChar(10)")]
		public string user_c_50
		{
			get
			{
				return this._user_c_50;
			}
			set
			{
				if ((this._user_c_50 != value))
				{
					this._user_c_50 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_51", DbType="NVarChar(20)")]
		public string user_c_51
		{
			get
			{
				return this._user_c_51;
			}
			set
			{
				if ((this._user_c_51 != value))
				{
					this._user_c_51 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_52", DbType="NVarChar(20)")]
		public string user_c_52
		{
			get
			{
				return this._user_c_52;
			}
			set
			{
				if ((this._user_c_52 != value))
				{
					this._user_c_52 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_53", DbType="NVarChar(20)")]
		public string user_c_53
		{
			get
			{
				return this._user_c_53;
			}
			set
			{
				if ((this._user_c_53 != value))
				{
					this._user_c_53 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_54", DbType="NVarChar(20)")]
		public string user_c_54
		{
			get
			{
				return this._user_c_54;
			}
			set
			{
				if ((this._user_c_54 != value))
				{
					this._user_c_54 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_55", DbType="NVarChar(20)")]
		public string user_c_55
		{
			get
			{
				return this._user_c_55;
			}
			set
			{
				if ((this._user_c_55 != value))
				{
					this._user_c_55 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_56", DbType="NVarChar(20)")]
		public string user_c_56
		{
			get
			{
				return this._user_c_56;
			}
			set
			{
				if ((this._user_c_56 != value))
				{
					this._user_c_56 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_57", DbType="NVarChar(20)")]
		public string user_c_57
		{
			get
			{
				return this._user_c_57;
			}
			set
			{
				if ((this._user_c_57 != value))
				{
					this._user_c_57 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_58", DbType="NVarChar(20)")]
		public string user_c_58
		{
			get
			{
				return this._user_c_58;
			}
			set
			{
				if ((this._user_c_58 != value))
				{
					this._user_c_58 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_59", DbType="NVarChar(20)")]
		public string user_c_59
		{
			get
			{
				return this._user_c_59;
			}
			set
			{
				if ((this._user_c_59 != value))
				{
					this._user_c_59 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_60", DbType="NVarChar(20)")]
		public string user_c_60
		{
			get
			{
				return this._user_c_60;
			}
			set
			{
				if ((this._user_c_60 != value))
				{
					this._user_c_60 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_61", DbType="NVarChar(20)")]
		public string user_c_61
		{
			get
			{
				return this._user_c_61;
			}
			set
			{
				if ((this._user_c_61 != value))
				{
					this._user_c_61 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_62", DbType="NVarChar(20)")]
		public string user_c_62
		{
			get
			{
				return this._user_c_62;
			}
			set
			{
				if ((this._user_c_62 != value))
				{
					this._user_c_62 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_63", DbType="NVarChar(20)")]
		public string user_c_63
		{
			get
			{
				return this._user_c_63;
			}
			set
			{
				if ((this._user_c_63 != value))
				{
					this._user_c_63 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_64", DbType="NVarChar(20)")]
		public string user_c_64
		{
			get
			{
				return this._user_c_64;
			}
			set
			{
				if ((this._user_c_64 != value))
				{
					this._user_c_64 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_65", DbType="NVarChar(40)")]
		public string user_c_65
		{
			get
			{
				return this._user_c_65;
			}
			set
			{
				if ((this._user_c_65 != value))
				{
					this._user_c_65 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_c_66", DbType="NVarChar(40)")]
		public string user_c_66
		{
			get
			{
				return this._user_c_66;
			}
			set
			{
				if ((this._user_c_66 != value))
				{
					this._user_c_66 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearb", DbType="NVarChar(10)")]
		public string bearb
		{
			get
			{
				return this._bearb;
			}
			set
			{
				if ((this._bearb != value))
				{
					this._bearb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearb_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> bearb_date
		{
			get
			{
				return this._bearb_date;
			}
			set
			{
				if ((this._bearb_date != value))
				{
					this._bearb_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bearb_time", DbType="Int")]
		public System.Nullable<int> bearb_time
		{
			get
			{
				return this._bearb_time;
			}
			set
			{
				if ((this._bearb_time != value))
				{
					this._bearb_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verantw_bereich", DbType="NVarChar(15)")]
		public string verantw_bereich
		{
			get
			{
				return this._verantw_bereich;
			}
			set
			{
				if ((this._verantw_bereich != value))
				{
					this._verantw_bereich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meinheit_pri", DbType="NVarChar(3)")]
		public string meinheit_pri
		{
			get
			{
				return this._meinheit_pri;
			}
			set
			{
				if ((this._meinheit_pri != value))
				{
					this._meinheit_pri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meinheit_sek", DbType="NVarChar(3)")]
		public string meinheit_sek
		{
			get
			{
				return this._meinheit_sek;
			}
			set
			{
				if ((this._meinheit_sek != value))
				{
					this._meinheit_sek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meinheit_ter", DbType="NVarChar(3)")]
		public string meinheit_ter
		{
			get
			{
				return this._meinheit_ter;
			}
			set
			{
				if ((this._meinheit_ter != value))
				{
					this._meinheit_ter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meinheit_bas", DbType="NVarChar(3)")]
		public string meinheit_bas
		{
			get
			{
				return this._meinheit_bas;
			}
			set
			{
				if ((this._meinheit_bas != value))
				{
					this._meinheit_bas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umrech_pri_zae", DbType="Int")]
		public System.Nullable<int> umrech_pri_zae
		{
			get
			{
				return this._umrech_pri_zae;
			}
			set
			{
				if ((this._umrech_pri_zae != value))
				{
					this._umrech_pri_zae = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umrech_pri_nen", DbType="Int")]
		public System.Nullable<int> umrech_pri_nen
		{
			get
			{
				return this._umrech_pri_nen;
			}
			set
			{
				if ((this._umrech_pri_nen != value))
				{
					this._umrech_pri_nen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umrech_sek_zae", DbType="Int")]
		public System.Nullable<int> umrech_sek_zae
		{
			get
			{
				return this._umrech_sek_zae;
			}
			set
			{
				if ((this._umrech_sek_zae != value))
				{
					this._umrech_sek_zae = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umrech_sek_nen", DbType="Int")]
		public System.Nullable<int> umrech_sek_nen
		{
			get
			{
				return this._umrech_sek_nen;
			}
			set
			{
				if ((this._umrech_sek_nen != value))
				{
					this._umrech_sek_nen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umrech_ter_zae", DbType="Int")]
		public System.Nullable<int> umrech_ter_zae
		{
			get
			{
				return this._umrech_ter_zae;
			}
			set
			{
				if ((this._umrech_ter_zae != value))
				{
					this._umrech_ter_zae = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umrech_ter_nen", DbType="Int")]
		public System.Nullable<int> umrech_ter_nen
		{
			get
			{
				return this._umrech_ter_nen;
			}
			set
			{
				if ((this._umrech_ter_nen != value))
				{
					this._umrech_ter_nen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verrech_gut", DbType="NVarChar(10)")]
		public string verrech_gut
		{
			get
			{
				return this._verrech_gut;
			}
			set
			{
				if ((this._verrech_gut != value))
				{
					this._verrech_gut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verrech_aus", DbType="NVarChar(10)")]
		public string verrech_aus
		{
			get
			{
				return this._verrech_aus;
			}
			set
			{
				if ((this._verrech_aus != value))
				{
					this._verrech_aus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verrech_nch", DbType="NVarChar(10)")]
		public string verrech_nch
		{
			get
			{
				return this._verrech_nch;
			}
			set
			{
				if ((this._verrech_nch != value))
				{
					this._verrech_nch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verrech_prb", DbType="NVarChar(10)")]
		public string verrech_prb
		{
			get
			{
				return this._verrech_prb;
			}
			set
			{
				if ((this._verrech_prb != value))
				{
					this._verrech_prb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gut_manu_takte", DbType="NChar(1)")]
		public System.Nullable<char> gut_manu_takte
		{
			get
			{
				return this._gut_manu_takte;
			}
			set
			{
				if ((this._gut_manu_takte != value))
				{
					this._gut_manu_takte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aus_manu_takte", DbType="NChar(1)")]
		public System.Nullable<char> aus_manu_takte
		{
			get
			{
				return this._aus_manu_takte;
			}
			set
			{
				if ((this._aus_manu_takte != value))
				{
					this._aus_manu_takte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nch_manu_takte", DbType="NChar(1)")]
		public System.Nullable<char> nch_manu_takte
		{
			get
			{
				return this._nch_manu_takte;
			}
			set
			{
				if ((this._nch_manu_takte != value))
				{
					this._nch_manu_takte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prb_manu_takte", DbType="NChar(1)")]
		public System.Nullable<char> prb_manu_takte
		{
			get
			{
				return this._prb_manu_takte;
			}
			set
			{
				if ((this._prb_manu_takte != value))
				{
					this._prb_manu_takte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nch_manu", DbType="NChar(1)")]
		public System.Nullable<char> nch_manu
		{
			get
			{
				return this._nch_manu;
			}
			set
			{
				if ((this._nch_manu != value))
				{
					this._nch_manu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prb_manu", DbType="NChar(1)")]
		public System.Nullable<char> prb_manu
		{
			get
			{
				return this._prb_manu;
			}
			set
			{
				if ((this._prb_manu != value))
				{
					this._prb_manu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vis_list3", DbType="NVarChar(10)")]
		public string vis_list3
		{
			get
			{
				return this._vis_list3;
			}
			set
			{
				if ((this._vis_list3 != value))
				{
					this._vis_list3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opt_mdetlg", DbType="NChar(1)")]
		public System.Nullable<char> opt_mdetlg
		{
			get
			{
				return this._opt_mdetlg;
			}
			set
			{
				if ((this._opt_mdetlg != value))
				{
					this._opt_mdetlg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auswmod", DbType="SmallInt")]
		public System.Nullable<short> auswmod
		{
			get
			{
				return this._auswmod;
			}
			set
			{
				if ((this._auswmod != value))
				{
					this._auswmod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vis_fhm_tnr_a_an", DbType="NChar(1)")]
		public System.Nullable<char> vis_fhm_tnr_a_an
		{
			get
			{
				return this._vis_fhm_tnr_a_an;
			}
			set
			{
				if ((this._vis_fhm_tnr_a_an != value))
				{
					this._vis_fhm_tnr_a_an = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bez_lang_1", DbType="NVarChar(40)")]
		public string bez_lang_1
		{
			get
			{
				return this._bez_lang_1;
			}
			set
			{
				if ((this._bez_lang_1 != value))
				{
					this._bez_lang_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bezeichnung_1", DbType="NVarChar(8)")]
		public string bezeichnung_1
		{
			get
			{
				return this._bezeichnung_1;
			}
			set
			{
				if ((this._bezeichnung_1 != value))
				{
					this._bezeichnung_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bez_lang_2", DbType="NVarChar(40)")]
		public string bez_lang_2
		{
			get
			{
				return this._bez_lang_2;
			}
			set
			{
				if ((this._bez_lang_2 != value))
				{
					this._bez_lang_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bezeichnung_2", DbType="NVarChar(8)")]
		public string bezeichnung_2
		{
			get
			{
				return this._bezeichnung_2;
			}
			set
			{
				if ((this._bezeichnung_2 != value))
				{
					this._bezeichnung_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bez_lang_18", DbType="NVarChar(40)")]
		public string bez_lang_18
		{
			get
			{
				return this._bez_lang_18;
			}
			set
			{
				if ((this._bez_lang_18 != value))
				{
					this._bez_lang_18 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bezeichnung_18", DbType="NVarChar(8)")]
		public string bezeichnung_18
		{
			get
			{
				return this._bezeichnung_18;
			}
			set
			{
				if ((this._bezeichnung_18 != value))
				{
					this._bezeichnung_18 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
